version: "3.9"

services:
  chats_postgres:
    image: pgvector/pgvector:pg18-trixie
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chats
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - chats_pg:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d chats"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

volumes:
  chats_pg:
